version: '3.8'

services:

  # Redis
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass password
    volumes:
      - redis-data:/data
    ports:
     - 6379:6379
    networks:
     - mlnet

  # Rabbitmq   
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq
    networks:
      - mlnet

  # API    
  ml-api:
    image: duynguyenngoc/mmip-api:latest
    container_name: ml-api
    restart: unless-stopped
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8081 --reload"
    volumes:
      - ./ml-storages:/storages/
      - api-logs:/logs/
    ports:
     - 8081:8081
    networks:
     - mlnet

  # Celery object detection
  ml-celery:
    image: duynguyenngoc/mmip-celery:latest
    container_name: ml-celery
    restart: unless-stopped
    command: sh -c "celery -A tasks worker --loglevel=info --concurrency=1 -E --logfile=/logs/celery.log"
    volumes:
      - ./ml-storages:/storages/
      - celery-logs:/logs/
    networks:
      - mlnet

  # Client demo
  ml-client:
    image: duynguyenngoc/mmip-client:latest
    environment:
      DOMAIN: localhost
      BE_HOST: ml-api
      BE_PORT: 8081
    container_name: ml-client
    restart: unless-stopped
    ports:
      - 80:80
    command: sh -c "./custom_nginx.sh && nginx -g 'daemon off;'"
    networks:
      - mlnet

networks:
  mlnet:

volumes:
  redis-data:
  rabbitmq-data:
  rabbitmq-logs:
  celery-logs:
  api-logs:
