version: '3.8'



services:

  # Redis
  redis:
    image: redis
    container_name: redis
    restart: unless-stopped
    command: redis-server --requirepass password
    volumes:
      - redis-data:/data
    ports:
     - 6379:6379
    networks:
     - mlnet

  # Rabbitmq   
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5672:5672
        - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=guest 
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/
      - rabbitmq-logs:/var/log/rabbitmq
    networks:
      - mlnet

  # API    
  ml-api:
    build:
      context: ./ml-api
      dockerfile: ./Dockerfile
    container_name: ml-api
    restart: unless-stopped
    command: sh -c "uvicorn main:app --host 0.0.0.0 --port 8081 --reload"
    volumes:
      - ./ml-api/app:/app/
      - ./ml-storages:/storages/
      - ./api-logs:/logs/
    ports:
     - 8081:8081
    networks:
     - mlnet

  # Celery object detection
  ml-celery:
    build: 
      context: ./ml-celery
      dockerfile: ./Dockerfile
    container_name: ml-celery
    restart: unless-stopped
    command: sh -c "celery -A tasks worker --loglevel=info --concurrency=1 -E --logfile=/logs/celery.log"
    volumes:
      - ./ml-celery/app:/app/
      - ./ml-storages:/storages/
      - ./celery-logs:/logs/
    networks:
      - mlnet

networks:
  mlnet:

volumes:
  redis-data:
  rabbitmq-data:
  rabbitmq-logs:
